name: Deploy Chat Agent to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: 173.212.251.191
      PROJECT_DIR: Madentk_chat_agent
      SERVICE_NAME: madentk-chat-agent.service
      APP_PORT: 8001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to server and run setup
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASS: ${{ secrets.SERVER_PASS }}
          REPO_URL: "https://github.com/ShehapAltahawy59/Madentk_chat_agent"
        run: |
          echo "Copying service template to server..."
          sshpass -p "$SERVER_PASS" scp -o StrictHostKeyChecking=no ./.deploy/madentk-chat-agent.service "$SERVER_USER@$SERVER_IP:/tmp/madentk-chat-agent.service"

          echo "Connecting to server..."
          sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "PROJECT_DIR='$PROJECT_DIR' SERVICE_NAME='${SERVICE_NAME:-madentk-chat-agent.service}' REPO_URL='$REPO_URL' GOOGLE_APPLICATION_CREDENTIALS='${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' Gemini_API_KEY='${{ secrets.Gemini_API_KEY }}' HUGGINGFACE_HUB_TOKEN='${{ secrets.HUGGINGFACE_HUB_TOKEN }}' bash -s" << 'EOF'
            set -e
            echo "Updating repo..."
            if [ ! -d "$PROJECT_DIR" ]; then
              mkdir -p "$PROJECT_DIR"
            fi
            cd "$PROJECT_DIR"

            if [ ! -d ".git" ]; then
              echo "Cloning repository for the first time..."
              git clone "$REPO_URL" .
            else
              git fetch --all --prune
              git reset --hard origin/main
            fi

            echo "Setting up virtual environment..."
            if [ ! -d "madentk-chat-agent-venv" ]; then
              python3 -m venv madentk-chat-agent-venv
            fi
            . madentk-chat-agent-venv/bin/activate

            echo "Installing requirements..."
            pip install --upgrade pip
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            else
              echo "requirements.txt not found; skipping."
            fi

            # Ensure start.sh is executable if present
            if [ -f start.sh ]; then
              chmod +x start.sh
            fi

            echo "Ensuring systemd service exists..."
            SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME"
            APP_DIR="$(pwd)"

            # Ensure env file exists with all necessary secrets
            echo "Writing /etc/madentk-chat-agent.env"
            {
              echo "GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-}"
              echo "Gemini_API_KEY=${Gemini_API_KEY:-}"
              echo "HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN:-}"
              echo "CHROMA_DB_DIR=/data/chroma_db"
            } | sudo tee /etc/madentk-chat-agent.env > /dev/null
            sudo chmod 600 /etc/madentk-chat-agent.env

            # Create log directory and set permissions
            echo "Creating log directory"
            sudo mkdir -p /var/log/madentk-chat-agent
            sudo chown $USER:$USER /var/log/madentk-chat-agent
            sudo chmod 755 /var/log/madentk-chat-agent

            if ! sudo test -f "$SERVICE_FILE"; then
              echo "Creating $SERVICE_NAME at $SERVICE_FILE"
              sudo sed -e "s|__APP_DIR__|$APP_DIR|g" \
                         -e "s|__RUN_USER__|$USER|g" \
                         /tmp/madentk-chat-agent.service | sudo tee "$SERVICE_FILE" > /dev/null
              sudo chmod 644 "$SERVICE_FILE"
              sudo systemctl daemon-reload
              sudo systemctl enable "$SERVICE_NAME"
            else
              echo "Service already exists; updating with latest template..."
              sudo sed -e "s|__APP_DIR__|$APP_DIR|g" \
                         -e "s|__RUN_USER__|$USER|g" \
                         /tmp/madentk-chat-agent.service | sudo tee "$SERVICE_FILE" > /dev/null
              sudo chmod 644 "$SERVICE_FILE"
              sudo systemctl daemon-reload
            fi

            echo "Restarting service..."
            sudo systemctl daemon-reload || true
            # Free port if any stray processes remain
            sudo fuser -k 8001/tcp || true
            sudo systemctl restart "$SERVICE_NAME"

            echo "Deployment complete!"
          EOF

      - name: Publish service URL
        id: publish-url
        run: |
          URL="http://${SERVER_IP}:${APP_PORT}"
          echo "url=${URL}" >> $GITHUB_OUTPUT
          echo "Service URL: ${URL}" >> $GITHUB_STEP_SUMMARY
